default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 

development:
  <<: *default
  database: jingsong_app_development

test:
  <<: *default
  database: jingsong_app_test

production:
  <<: *default
  database: jingsong_app_production

